version: '3'
services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - "./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro"

  hkweb:
    build:
      context: ./hkweb
    ports:
      - "8081:80"
    volumes:
      - "./hkweb/config/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./hkweb/data/html:/etc/nginx/html:ro"
